version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
jobs:
  test-ruby:
    # Install gems, run rspec tests
    docker:
      - image: cimg/ruby:3.3.4-node
        environment:
          PG_HOST: localhost
          PG_USER: postgres
          RAILS_ENV: test
          DATABASE_URL: "postgres://postgres@localhost:5432/postgres"
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: rspec test
          command: bundle exec rspec
workflows:
  build-and-test:
    jobs:
      - test-ruby
